taxonomy: topic
_id: stack
name: Stack
shortname: Stack
parent: Algorithm
keywords:
  - stack
images:
  - https://smartableai.github.io/algorithm/assets/images/topics/stack.jpg
services:
  learning: https://smartableai.github.io/algorithm/api/learning/stack/
  challenges: https://smartableai.github.io/algorithm/api/challenges/stack/
