#----------------------------------------------------------------------------------
# Site Settings
#----------------------------------------------------------------------------------

title: Algorithm Smartable
url: https://smartableai.github.io
baseurl: "/algorithm"
webUrl: https://smartable.ai/apps/algorithm
locale: "en-us"
charset: utf-8
repository: SmartableAI/algorithm
topic: Algorithm


#----------------------------------------------------------------------------------
# Post Settings
#----------------------------------------------------------------------------------

# The permalink of posts
# For multilingual site, /:path/ is the only global permalink setting that works.
# Other permalink settings cannot prepend the post locale to the URL.
permalink: /:year/:month/:day/:title/

# Default settings of posts
default_post_settings: &default_post_settings
  layout: post
  permalink: /api/:categories/:year/:month/:day/:title/index.json
  deleted: false
  related: true

pagination:
  page_size: 20


#----------------------------------------------------------------------------------
# Challenge Settings
#----------------------------------------------------------------------------------

# Default settings of challenges
default_challenge_settings: &default_challenge_settings
  layout: post
  category: challenge
  permalink: /api/challenges/:path/index.json
  deleted: false


#----------------------------------------------------------------------------------
# Form Settings
#----------------------------------------------------------------------------------

# Default settings of forms
default_form_settings: &default_form_settings
  layout: post
  category: form
  permalink: /api/forms/:path/index.json
  deleted: false


#----------------------------------------------------------------------------------
# Newsletter Settings
#----------------------------------------------------------------------------------

# Default settings of newsletter issues
default_newsletter_settings: &default_newsletter_settings
  layout: post
  category: newsletter
  permalink: /api/newsletters/:path/index.json
  deleted: false


#----------------------------------------------------------------------------------
# System Settings
# DO NOT CHANGE if you do not know what you are doing
#----------------------------------------------------------------------------------

collections:
  terms:
    output: true
  sponsorships:
    output: true
  posts:
    output: true
  challenges:
    output: true
  forms:
    output: true
  newsletters:
    output: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      <<: *default_post_settings
  # _challenges
  - scope:
      path: ""
      type: challenges
    values:
      <<: *default_challenge_settings
  - scope:
      path: "_challenges/collections"
    values:
      layout: collection
      category: challenge
      permalink: /api/challenges/collections/:title/index.json
      type: collection
      support_paging: false
  # _forms
  - scope:
      path: ""
      type: forms
    values:
      <<: *default_form_settings
  - scope:
      path: "_forms/collections"
    values:
      layout: collection
      category: form
      permalink: /api/forms/collections/:title/index.json
      type: collection
      support_paging: false
  # _newsletters
  - scope:
      path: ""
      type: newsletters
    values:
      <<: *default_newsletter_settings
  # apis
  - scope:
      path: "api/*/*"
    values:
      layout: collection
      permalink: /:path/index.json
      support_paging: true


# Use the following Jekyll plug-ins
plugins:
  - jekyll-redirect-from
  - jekyll-relative-links # Convert relative links to md files to their rendered equivalents
  - jemoji # Enable Emoji
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true

include:
  - .htaccess

# Exclude these files from your production _site
exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - .cache
  - .sass-cache

remote_theme: SmartableAI/build
incremental: true
